src/__tests__/compiler.test.tsx
src/__tests__/quantifiers.test.tsx
src/utils.ts

Use a non-capturing group to wrap multiline patterns for quantifiers. 
Added tests to detect capture group presence in the output.

fix: use non-capturing group to wrap multicharacter patterns

---

src/compiler.ts
src/quantifiers.ts
src/types-internal.ts
src/types.ts

refactor: rename `RegexComponent` to `RegexElement`

---

src/__tests__/compiler.test.tsx
src/__tests__/repeat.test.tsx
src/compiler.ts
src/quantifiers/index.ts
src/quantifiers/repeat.ts
src/types.ts

This PR implements `repeat()` utility. I still need to figure out how to properly type it
Passings tests

feat: `repeat` quantifier

---

GUIDELINES.md
README.md

docs: project guidelines

---

.gitignore
src/__tests__/compiler.test.tsx
src/compiler.ts
src/utils.ts

Escape special characters when passed in string form. 
Resolves #14 
Added relevant tests for all special characters described by MDN docs.

feat: escape special characters

---

src/__tests__/capture.test.tsx
src/capture.ts
src/encoder.ts
src/test-utils.ts
src/types.ts

Base (non-named) `capture` operator.
Added basic tests.

feat: base (non-named) capture

---

src/__tests__/builder.test.ts
src/builders.ts
src/utils.ts

feat: support core regex flags

---

jest-setup.ts
package.json
src/__tests__/builder.test.ts
src/components/__tests__/capture.test.tsx
src/components/__tests__/character-class.test.ts
src/components/__tests__/choice-of.test.ts
src/components/__tests__/quantifiers.test.tsx
src/components/__tests__/repeat.test.tsx
src/components/character-class.ts
src/encoder/__tests__/encoder.test.tsx
src/encoder/encoder.ts
src/test-utils.ts
src/utils.ts
test-utils/to-have-pattern.ts
test-utils/to-match-groups.ts

Simplify test by introducing `toHavePattern` & `toMatchGroups` custom Jest matchers
Modified tests.

refactor: `toHavePattern` & `toMatchGroups` matchers

---

README.md
src/components/__tests__/character-class.test.ts
src/components/character-class.ts
src/components/types.ts

```ts
test('"characterRange" base cases', () => {
expect(buildPattern(characterRange('a', 'z'))).toBe('[a-z]');
expect(buildPattern('x', characterRange('0', '9'))).toBe('x[0-9]');
expect(buildPattern(characterRange('A', 'F'), 'x')).toBe('[A-F]x');
});
test('"characterClass" base cases', () => {
expect(
buildPattern(
characterClass(characterRange('a', 'z'), characterRange('A', 'Z'))
)
).toBe('[a-zA-Z]');
expect(
buildPattern(
characterClass(characterRange('a', 'z'), anyOf('05')) 
)
).toBe('[a-z05]');
expect(
buildPattern(
characterClass(characterRange('a', 'z'), whitespace)
)
).toBe('[a-z\\s]');
});```
Added tests.

feat: `characterClass` & `characterRange`

---

src/components/__tests__/anchors.test.tsx
src/components/anchors.ts
src/components/types.ts
src/encoder/encoder.ts

feat: base anchors

---

src/components/__tests__/quantifiers.test.tsx
src/components/quantifiers.ts
src/encoder/__tests__/encoder.test.tsx
src/index.ts

* remove `one` component as unnecessary
* add missing package exports

refactor: remove `one` component

---

.editorconfig
README.md
docs/Examples.md
src/__tests__/builder.test.ts
src/__tests__/examples.ts
src/builders.ts
src/components/__tests__/capture.test.tsx
src/components/__tests__/character-class.test.ts
src/components/__tests__/choice-of.test.ts
src/components/__tests__/repeat.test.tsx
src/components/character-class.ts
src/components/choice-of.ts
src/components/repeat.ts
src/encoder/__tests__/encoder.test.tsx
src/encoder/encoder.ts
test-utils/to-have-pattern.ts
test-utils/to-match-groups.ts
tsconfig.json

fix: character class escaping

---

README.md
docs/Examples.md
src/__tests__/examples.ts
src/components/__tests__/character-class.test.ts
src/components/character-class.ts
src/index.ts

Change following names to shorter:
- `characterClass` => `charClass`
- `characterRange` =>`charRange`
The usage of `characterClass` & `characterRange` (frequently together) creates lengthy expressions.
```ts
const hexDigit = characterClass(
characterRange('a', 'f'),
characterRange('A', 'F'),
characterRange('0', '9')
);
```
These names are much longer then other regex components (`anyOf`, `capture`, `oneOrMore`, etc.), yet are relatively frequently used. In order to reduce the taken space I propose using `char` instead of `character` in their names.
```ts
const hexDigit = charClass(charRange('a', 'f'), charRange('A', 'F'), charRange('0', '9'));
```
The `char` abbreviation is already used in 1st party JS APIs: e.g.,:
- `String.charAt()`
- `String.charCodeAt()`
- `String.fromCharCode()` …

refactor(rfc): abbreviate `charClass` and `charRange`

---

README.md
package.json
src/components/__tests__/character-class.test.ts
src/components/character-class.ts

fix: char class `^-` edge case

---

docs/API.md
src/components/anchors.ts
src/components/capture.ts
src/components/choice-of.ts
src/components/quantifiers.ts
src/components/repeat.ts
src/encoder/encoder.ts
src/types.ts
src/utils/nodes.ts
test-utils/utils.ts

Improve type naming;
* `RegexElement` => `RegexEncodable`
* `RegexNode` => `RegexElement`

refactor: rename types

---

README.md
docs/API.md
docs/Examples.md
src/__tests__/examples.test.ts
src/constructs/__tests__/choice-of.test.ts
src/constructs/__tests__/repeat.test.tsx
src/constructs/repeat.ts

Simplify exact count repeat quantifiers: `repeat(..., { count: 3 })` => `repeat(..., 3)`.
The min/max syntax stays the same: `repeat(..., { min: 2 })`, `repeat(..., { min: 1, max: 5})`

refactor: simplify exact repeat quantifier

---

README.md
docs/API.md
docs/Examples.md
src/__tests__/builder.test.ts
src/__tests__/examples.test.ts
src/builders.ts
src/constructs/repeat.ts
src/types.ts

docs: api docs

---

README.md
docs/API.md
docs/Examples.md
src/__tests__/examples.test.ts
src/constructs/__tests__/character-class.test.ts
src/constructs/__tests__/quantifiers.test.tsx
src/constructs/quantifiers.ts
src/encoder/__tests__/encoder.test.tsx
src/index.ts

Preparing code examples I've noticed that `optional` quantifier name made more sense then Swift's `Optionally`. After some research I've noted that Swift already has a general purpose `Optional` type, which probably caused need to duplicating it. In our case we are free from such limitations and we can use simple and better `optional` name.

refactor: rename `optionally` to `optional`

---

README.md
docs/API.md
docs/Examples.md

docs: proof-read docs

---

README.md
docs/API.md
src/encoder/__tests__/encoder.test.tsx
src/encoder/encoder.ts
src/types.ts

Adds ability to pass RegExp literals (or objects) as regex elements to allow mixing of simple regex literals (e.g. char classes) with structural regex builder calls.

feat: mix with regexp object

---

README.md
docs/API.md
src/constructs/__tests__/quantifiers.test.tsx
src/constructs/__tests__/repeat.test.tsx
src/constructs/quantifiers.ts
src/constructs/repeat.ts

This PR implements "lazy" (== "non-greedy") variants of base quantifiers (`??`, `*?`, `+?`) and repeat (`{...}?`).
This PR  currently uses following syntax, simulating Swift enums in JS convention:
```ts
optional([...], "lazy");
zeroOrMore([...], "lazy");
oneOrMore([...], "lazy");
repeat([...], 3, "lazy");
repeat([...], { min: 1, max: 5 }, "lazy");
```
This feature could also use some alternative syntax, here are couple of possible versions:
1. "lazy" as prefix:
```ts
lazyOptional([...]);
lazyZeroOrMore([...]);
lazyOneOrMore([...]);
lazyRepeat([...], 3);
lazyRepeat([...], { min: 1, max: 5 });
```
2. "lazy" as suffix:
```ts
optionalLazy([...]);
zeroOrMoreLazy([...]);
oneOrMoreLazy([...]);
repeatLazy([...], 3);
repeatLazy([...], { min: 1, max: 5 });
```
3. "lazy"  as named option
```ts …
```

feat: non-greedy quantifiers

---

README.md
docs/API.md
docs/Examples.md
src/__tests__/example-find-suffixes.ts
src/__tests__/example-find-words.ts
src/constructs/__tests__/anchors.test.tsx
src/constructs/__tests__/capture.test.tsx
src/constructs/__tests__/character-class.test.ts
src/constructs/__tests__/choice-of.test.ts
src/constructs/__tests__/lookahead.test.ts
src/constructs/__tests__/lookbehind.test.ts
src/constructs/__tests__/negative-lookahead.test.ts
src/constructs/__tests__/negative-lookbehind.test.ts
src/constructs/__tests__/quantifiers.test.tsx
src/constructs/__tests__/repeat.test.tsx
src/constructs/anchors.ts
src/encoder/encoder.ts
src/index.ts
test-utils/to-match-string.ts

Implement `wordBoundary` anchors (as well as their negation).
**Checklist**
Add relevant tests.

feat: `wordBoundary` anchor

---

package.json
src/patterns/__tests__/hex-color.test.ts
src/patterns/hex-color.ts
src/patterns/index.ts

First of the series of common patters: hex color.
This PR defined `finder` and `validator` variants for hex color pattern.
Note this feature will not be yet mentioned in the documentation to confirm that commonjs/esm import works as intended after release.

feat: common patterns infrastructure (hex color)

---

src/constructs/__tests__/character-class.test.ts
src/constructs/character-class.ts

Fixe #75 
Added automated tests.

fix: proper encoding for `any('.')`

---

src/__tests__/example-js-number.ts
src/constructs/__tests__/regex.test.tsx
src/constructs/regex.ts
src/index.ts
website/docs/api/constructs.md

`regex` construct: no-op grouping for easier nesting
Added automated tests.

feat: `regex` construct

---

package.json

chore: add js file extension for exports

---

src/__tests__/builder.test.ts
src/builders.ts
src/types.ts
website/docs/api/builder.md

Add `dotAll` and `sticky` regex flags.
Added automated tests

feat: `dotAll` & `sticky` options

---

src/constructs/__tests__/character-class.test.ts
src/constructs/character-class.ts
src/encoder/encoder.ts
src/types.ts

`any` (regex: `.`) could be added to char class
```
any // => /./ - ok matches any char
charClass(any) // => /[.]/ - not ok, `.` in char class looses special meaning and matchers literal dot
```
Adapt automated tests

fix: prevent embedding `any` (`.`) in `charClass`

---

src/constructs/__tests__/char-class.test.ts
src/constructs/__tests__/char-escape.test.ts
src/constructs/__tests__/lookahead.test.ts
src/constructs/__tests__/lookbehind.test.ts
src/constructs/__tests__/negative-lookahead.test.ts
src/constructs/char-class.ts
src/constructs/char-escape.ts
src/index.ts
src/patterns/hex-color.ts

refactor: char escapes handling

---

README.md
src/builders.ts
src/constructs/__tests__/char-class.test.ts
src/constructs/__tests__/encoder.test.tsx
src/constructs/anchors.ts
src/constructs/capture.ts
src/constructs/char-class.ts
src/constructs/char-escape.ts
src/constructs/choice-of.ts
src/constructs/lookahead.ts
src/constructs/lookbehind.ts
src/constructs/negative-lookahead.ts
src/constructs/negative-lookbehind.ts
src/constructs/quantifiers.ts
src/constructs/regex.ts
src/constructs/repeat.ts
src/encoder.ts
src/encoder/encoder.ts
src/encoder/types.ts
src/types.ts
src/utils/elements.ts
src/utils/text.ts
test-utils/utils.ts
website/docs/api/assertions.md
website/docs/api/captures.md
website/docs/api/character-classes.md
website/docs/api/constructs.md
website/docs/api/overview.md
website/docs/api/quantifiers.md
website/docs/api/types.md

refactor: simplify encoders
